services:
  appserver:
    container_name: appserver
    build: ./server_part5

  proxyserver:
    container_name: proxyserver
    image: nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx_compose/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - appserver
